---
title: "BUSCO plots"
author: "Jill Ashey"
date: "2024-12-03"
output: html_document
---

BUSCO was run to evaluate completeness of our genome (Acropora pulchra), and the A. millepora, A. digitifera, A. cervicornis, and A. palmata genomes. This script will plot these results to compare completeness across Acropora spp. genomes.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(forcats)
```

Load busco comparison data
```{r}
busco <- read.csv("../Tables/BuscoComparisons.csv")
```

Reshape data to long format 
```{r}
busco_long <- pivot_longer(busco, 
                           cols = c("Complete_single_copy_percent", "Complete_duplicate_percent", "Fragmented_percent", "Missing_percent"),
                           names_to = "Category",
                           values_to = "Percentage")
```

Reorder categories for plotting 
```{r}
# Rename and reorder categories
busco_reordered <- busco_long %>%
  mutate(Category = factor(Category,
                           levels = c("Complete_single_copy_percent", 
                                      "Complete_duplicate_percent", 
                                      "Fragmented_percent", 
                                      "Missing_percent"),
                           labels = c("Complete & single copy (Cs)",
                                      "Complete & duplicate copy (Cd)",
                                      "Fragmented (F)",
                                      "Missing (M)")),
         Species = factor(Species, 
                          levels = c("Acropora palmata", "Acropora cervicornis", "Acropora digitifera", "Acropora millepora", "Acropora pulchra"))) %>%
  group_by(Species) %>%
  arrange(desc(Percentage), .by_group = TRUE) %>%
  ungroup()

# Create a separate dataframe for labels
label_data <- busco_reordered %>%
  group_by(Species) %>%
  summarise(Label = case_when(
    Species == "Acropora pulchra" ~ "Cs = 95.1%, Cd = 1.6%, F = 0.9%, M = 2.4%",
    Species == "Acropora millepora" ~ "Cs = 87.2%, Cd = 5.5%, F = 2.6%, M = 4.7%",
    Species == "Acropora palmata" ~ "Cs = 85.8%, Cd = 6.7%, F = 3.6%, M = 3.9%",
    Species == "Acropora digitifera" ~ "Cs = 92.8%, Cd = 0.4%, F = 3.4%, M = 3.4%",
    Species == "Acropora cervicornis" ~ "Cs = 73.2%, Cd = 7.7%, F = 3.9%, M = 15.2%",
    TRUE ~ ""
  ))
```

Plot 
```{r}
ggplot(busco_reordered, aes(x = Species, y = Percentage, fill = fct_rev(Category))) +
  geom_bar(stat = "identity", position = "fill", width = 0.7, color = "black") +
  # geom_text(aes(label = ifelse(Species == "Acropora pulchra", "sup", "")),
  #           position = position_fill(vjust = 0.5),
  #           color = "white", size = 4, fontface = "bold") +
  geom_text(data = label_data, aes(x = Species, y = 0.5, label = Label), 
            color = "black", 
            size = 5,
            inherit.aes = F) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), expand = c(0, 0)) +
  scale_fill_manual(values = c("#22177A", "#605EA1", "#8EA3A6", "#E6E9AF")) +
  coord_flip() +
  labs(x = NULL,
       y = "Percentage",
       fill = "BUSCO Category") +
  theme_minimal() +
  theme(
    axis.text.y = element_text(face = "italic", color = "black", size = 20),
    axis.title.x = element_text(size = 23),
    axis.text.x = element_text(color = "black", size = 20),
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    #panel.grid.major.y = element_line(color = "black"),
    axis.line.y = element_line(color = "black"),
    panel.grid.major = element_line(color = "black"),
    panel.grid.minor = element_blank()) +
  guides(fill = guide_legend(reverse = TRUE))

# Save 
ggsave("../output/assembly/ntlink/busco_comparisons.pdf", plot = last_plot(), width = 15, height = 10)
ggsave("../output/assembly/ntlink/busco_comparisons.png", plot = last_plot(), width = 15, height = 10)
```

